main:
	-rm -v a.out 
	-rm -v Test/*_*.p?m 
	-rm -v Boat/*_*.p?m 
	-rm -v Graf/*_*.p?m 
One: main
	g++ PartOne.cpp -g -Wall
	./a.out Test/Test1
	./a.out Test/Test2
	./a.out Test/Test3
Two: main
	g++ PartTwo.cpp -g -Wall
	./a.out Boat/img1
	./a.out Boat/img3
	./a.out Boat/img5
	./a.out Graf/img1
	./a.out Graf/img3
	./a.out Graf/img5
